---
- name: restart sshd
  service: name=ssh state=restarted

- name: reload nullmailer
  service: name=nullmailer state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded
